Repository diggging/diggging_react, pull requests merged in 2022-04, with the labels that each got.

#14 Feature/search
  components/search/CardContainer/index.jsx
  components/search/ListCard/index.jsx
  components/search/ListCard/style.js
  components/search/SearchInput/index.jsx
Labels: 이슈해결🥞, 스타일링🍈

#13 user
  components/accountSetting/PasswordSetBox/index.jsx
  components/accountSetting/PasswordSetBox/style.js
  components/accountSetting/ProfileInfoBox/index.jsx
  pages/accountSetting.js
  pages/findPassword.js
  pages/signup.js
  pages/userActivated.js
  redux/actions/auth.js
Labels: 에러해결💥, 이슈해결🥞

#15 search - pagination구현
  components/search/SearchInput/index.jsx
  pages/search.js
Labels: 기능구현🍕, 이슈해결🥞

#16 navBar 프로필사진 화질개선 및 css
  components/common/NavBar/index.jsx
  components/common/NavBar/style.js
Labels: 기능구현🍕, 이슈해결🥞

#17 [FIX] 폰트 오타 수정
  components/comment/questionComment/SingleComment/style.js
Labels: 이슈해결🥞

#20 [FIX] url 경로 문제 해결(find_password)
  pages/login_page.js
  pages/password_reset_submit.js
  pages/signup.js
Labels: 에러해결💥
