Repository diggging/diggging_react, pull requests merged in 2022-03, with the labels that each got.

#3 Feature/refactor
  .eslintrc.js
  components/accountSetting/BioUpdateBox/index.jsx
  components/accountSetting/PasswordSetBox/style.js
  components/accountSetting/ProfileInfoBox/style.js
  components/answer/Answers/index.jsx
  components/answer/AnswersList/index.jsx
  components/questions/PreventRerender.js
  pages/_app.js
  pages/_document.js
  pages/aboutus.js
  pages/accountSetting.js
  pages/findPassword.js
  pages/index.js
  pages/loginPage.js
  pages/main.js
  pages/mine.js
  pages/mypage.js
  pages/password_reset_submit.js
  pages/popular.js
  pages/questionCreate.js
  pages/recent.js
  pages/search.js
  pages/signup.js
  public/static/fonts/Pretendard-Bold.eot
  public/static/fonts/Pretendard-Bold.subset.woff
  public/static/fonts/Pretendard-Bold.subset.woff2
  public/static/fonts/Pretendard-Bold.ttf
  public/static/fonts/Pretendard-Bold.woff
  public/static/fonts/Pretendard-ExtraBold.eot
  public/static/fonts/Pretendard-ExtraBold.subset.woff
  public/static/fonts/Pretendard-ExtraBold.subset.woff2
  public/static/fonts/Pretendard-ExtraBold.ttf
  public/static/fonts/Pretendard-ExtraBold.woff
  public/static/fonts/Pretendard-Light.subset.woff
  public/static/fonts/Pretendard-Light.subset.woff2
  public/static/fonts/Pretendard-Light.ttf
  public/static/fonts/Pretendard-Medium.eot
  public/static/fonts/Pretendard-Medium.subset.woff
  public/static/fonts/Pretendard-Medium.subset.woff2
  public/static/fonts/Pretendard-Medium.ttf
  public/static/fonts/Pretendard-Medium.woff
  public/static/fonts/Pretendard-Regular.eot
  public/static/fonts/Pretendard-Regular.subset.woff
  public/static/fonts/Pretendard-Regular.subset.woff2
  public/static/fonts/Pretendard-Regular.ttf
  public/static/fonts/Pretendard-Regular.woff
  public/static/fonts/Pretendard-SemiBold.eot
  public/static/fonts/Pretendard-SemiBold.subset.woff
  public/static/fonts/Pretendard-SemiBold.subset.woff2
  public/static/fonts/Pretendard-SemiBold.ttf
  public/static/fonts/Pretendard-SemiBold.woff
  public/static/fonts/font.css
  redux/actions/auth.js
  redux/reducers/auth.js
Labels: 리팩토링⚙, 에러해결💥, 최적화⚗, 구조변경🛠

#5 [ADD]디깅소개 추가(노션페이지연결)
  components/common/NavBar/index.jsx
Labels: 기능구현🍕

#8 Feature/tag input
  components/answer/ToastAnswerCreate/index.jsx
  components/answer/ToastAnswerUpdate/index.jsx
  components/comment/answerComment/AnswerCommentList/index.jsx
  components/comment/questionComment/CommentList/index.jsx
  components/questions/PreventRerender/style.js
  components/questions/QuestionList/index.jsx
  components/questions/ToastUiCreate/index.jsx
  components/questions/ToastUiUpdate/index.jsx
  pages/questionCreate.js
  pages/questions/[id].js
Labels: 리팩토링⚙, 에러해결💥

#6 Feature/resize
  components/common/NavBar/style.js
  pages/index.js
  public/static/images/Alarm.js
  public/static/images/AnswerIcon.js
  public/static/images/AnswerSelectedIcon.js
  public/static/images/BookMarkIcon.js
  public/static/images/CloseIcon.js
  public/static/images/CommentIcon.js
  public/static/images/DefaultProfileImg.js
  public/static/images/Diggging.js
  public/static/images/DigggingLogo.js
  public/static/images/DigggingLogoResize.js
  public/static/images/Directory.js
  public/static/images/EditIcon.js
  public/static/images/HeartIcon.js
  public/static/images/Search.js
  public/static/images/ToggleBtn.js
  public/static/images/index.js
  public/static/images/svg/digggingLogoResize.svg
Labels: 리팩토링⚙, 리사이징🧃

#7 Feature/refactor
  .eslintrc.js
  pages/answer/create/[id].js
  pages/answer/update/[id].js
  pages/api/account/login.js
  pages/api/account/logout.js
  pages/api/account/refresh.js
  pages/api/account/register.js
  pages/api/account/reset_password.js
  pages/api/account/reset_password_confirm.js
  pages/api/account/user.js
  pages/api/account/verify.js
  pages/questions/[id].js
  pages/questions/update/[id].js
  pages/users/password_reset/done.js
  pages/users/password_reset/index.js
Labels: 에러해결💥
